name: Publish Site

on:
  push:
    branches:
      - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chain-ed-reaction/bee-lab@gh-pages
        with:
          githubToken: ${{ secrets.hugo_website }}
        env:
          HUGO_VERSION: 0.57.2
          TARGET_REPO: chain-ed-reaction/bee-lab@gh-pages
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '-t hugogreyscale'
          #CNAME: benmatselby.github.io
