on: push
name: Deploy to GitHub Organization Pages
jobs:
  filtersForGitHubActions:
    name: Filters for GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filters for GitHub Actions
      uses: actions/bin/filter@master
      with:
        args: branch gh-pages
    - name: hugo-deploy-gh-org-pages
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.hugo_website }}
        # Remember to set this as a secret (i.e. secrets.PERSONAL_TOKEN).
        # Don't forget to set the secret value in the project settings.
        #cname: mysite.com # Or anything else
        # Use if you have a custom domain for your site.
        hugoVersion: extended_0.58.3
        # Use if your site requires a specific version of Hugo
        # Append "extended_" to the begining to use Hugo Extended
        args: -t hugogreyscale
        # Use if you want to pass some custom arguments to Hugo
